[build]
  command = "npm ci && npm run build"
  publish = "dist"
  base = "."
  environment = { NODE_VERSION = "18" }

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  # Explicitly indicate this is NOT a Go project
  GO_IMPORT_PATH = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200